### ISSUE TITLE
Panic if the hot key is registered

### ISSUE THREAD

**Issue by asuper0** [Vadoola/Tomotroid#54]
```
thread 'main' panicked at src\main.rs:137:38:
called `Result::unwrap()` on an `Err` value: AlreadyRegistered(HotKey { mods: Modifiers(CONTROL), key: F1, id: 4165587127 })
```
Suggest to change type of the three field of `Tomotroid` from `HotKey` to `Option<HotKey>`, that allows them to be disabled.

**Comment by Vadoola** [comment]
Resolved in commit 1c88e80e51034754e04529b17d95ff57df60574e as part of [pull request 56](https://github.com/Vadoola/Tomotroid/pull/56)
