### ISSUE TITLE
Panic because the settings

### ISSUE THREAD

**Issue by asuper0** [Vadoola/Tomotroid#55]
Panic when [matching theme](https://github.com/Vadoola/Tomotroid/blob/main/src/main.rs#L149)
The json files are not existed in `C:\Users\Administrator\AppData\Roaming\Vadoola\Tomotroid\config\`. So `settings::load_settings();` get a default setting, which "theme" is "Pomotroid", while the default theme is named "Rangitoto".
I solved it by change default theme to "Rangitoto".

Panic when [save settings](https://github.com/Vadoola/Tomotroid/blob/main/src/settings.rs#L315)
Because the folder `C:\Users\Administrator\AppData\Roaming\Vadoola\Tomotroid\config\` is not exised. Must check the folder before saving.

**Comment by Vadoola** [comment]
Resolved with [pull request 56](https://github.com/Vadoola/Tomotroid/pull/56)
