### ISSUE TITLE
it can not successed run code in debug mode in windows, it  successed  in release mode

### ISSUE THREAD

**Issue by iincity** [Vadoola/Tomotroid#82]
process didn't exit successfully: `target\debug\tomotroid.exe` (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)

**Comment by Vadoola** [comment]
Hi Thanks for reporting this. I actually was aware of this, but never documented it (as I should have). Unfortunately it is an upstream issue, and I haven't spent a lot of time on it. Based on [Slint issue #3375](https://github.com/slint-ui/slint/issues/3375), it's possible it can be resolved by increasing the Windows stack limit in the MSVC linker. I hadn't bothered to try changing the stack limit yet, but I just did and it appears to work.

So my quick test was I created a .cargo/config.toml, and added the below code increasing the Windows stack from 1mb to 2mb:
`
[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "link-arg=/STACK:2000000"
]
`
and sure enough it compiled and ran.

Possibly Relevant Slint Issues / Discussions:
- https://github.com/slint-ui/slint/issues/133
- https://github.com/slint-ui/slint/issues/3375
- https://github.com/slint-ui/slint/issues/4586
- https://github.com/slint-ui/slint/discussions/5058.

**Comment by Vadoola** [comment]
This has been resolved with the addition of the config.toml increasing the stack size on windows (commit 7cc5e7a)
